dist: bionic
language: minimal
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common uidmap
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install podman
install:
  - travis_retry podman build --rm -t test/rpm-build .
before_script:
  - git clone https://src.fedoraproject.org/rpms/ruby.git
script:
  - |
    podman run --rm -t -v $(pwd)/ruby:/work/ruby -u root test/rpm-build bash -cx "cd ruby && fedpkg srpm"
  - |
    ls $(pwd)/ruby/*.src.rpm
branches:
  except:
    - /^wip\//
